# Generated by Django 5.2.8 on 2025-12-01 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',  # اسم النموذج الذي يحتوي على الحقل
            name='is_completed',
            field=models.BooleanField(default=False),)
    ]
